# ç”Ÿæˆç½‘å€æ‰€ç”¨åŸŸå
baseURL = "https://bonfire8458.github.io/"
# è¯­è¨€ç¼–ç (ä¸­æ–‡: zh-CN)
languageCode = "zh-cn"
# é»˜è®¤çš„å†…å®¹è¯­è¨€
defaultContentLanguage = "zh-cn"
# åˆ›å»ºrobots.txtï¼Œå»ºè®®è®¾ç½®ä¸ºtrue
enableRobotsTXT = false
# å¯ç”¨ Emoji; see emoji-cheat-sheet.com
enableEmoji = true
# è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å«ä¸­æ–‡/æ—¥æ–‡/éŸ©æ–‡ï¼Œè¯¥å‚æ•°ä¼šå½±å“æ‘˜è¦å’Œå­—æ•°ç»Ÿè®¡åŠŸèƒ½ï¼Œå»ºè®®è®¾ç½®ä¸ºtrueã€‚Hugoä¼šè‡ªåŠ¨æå–æ–‡ç« çš„å‰70ä¸ªå­—ç¬¦ä½œä¸ºæ‘˜è¦ï¼ŒhasCJKLanguage = trueæ‰èƒ½å‘æŒ¥æ›´å¥½çš„æ•ˆæœã€‚
hasCJKLanguage = true
title = "å§†QğŸ€çš„å¤§åœ–æ›¸é¤¨"
# ä¸»é¢˜
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    identifier = "links"
    name = "Links"
    url = "/links/"
    weight = 5
  

[params]
  author = "Bonfire8458"
  avatar = "./images/favicon.png"
  favicon = "./images/favicon.png"
  #description = "* ç§‰æŒå‹‡æ°”ä¸æ™ºæ…§ï¼Œæ‹¿èµ·å¿ƒç†å­¦è¿™æ ¹é­”æ–ï¼ŒèˆåŠ¨å½“ä¸‹</p><p>* å’–å•¡ç»­å‘½ä¸­ing..."
  description = "å’–å•¡ç»­å‘½ä¸­ing... // GPG Key ID: 3A558BBF2AF694FF"
  

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/Bonfire8458"

  [[params.social]]
    icon = "X"
    name = "Twitter"
    url = "https://x.com/Bonfire8458"

  [[params.social]]
    icon = "send"
    name = "Telegram"
    url = "https://t.me/bonfire8458"
  
  [[params.social]]
    icon = "Matrix"
    name = "matrix"
    url = "https://matrix.to/#/@bonfire8458:matrix.org"

  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:Unending2924@gmail.com"

  [[params.social]]
    icon = "reddit"
    name = "Reddit"
    url = "https://www.reddit.com/user/Bonfire8458/"

[params.style]
  # å·¦èƒŒæ™¯è‰²
  darkestColor = "#040305"
  # å³èƒŒæ™¯è‰²
  darkColor = "#38373A"
  # æ­£æ–‡å­—è‰²
  lightColor = "#E6F2EC"
  # æ ‡é¢˜å­—è‰²
  lightestColor = "#E5E572"
  # åœˆåœˆã€é“¾æ¥è‰²
  primaryColor = "#A970D8"

[markup]
  [goldmark.renderer]
# ä¸æ¸²æŸ“å†…åµŒçš„ HTML 
# unsafe = true
  [markup.highlight]
    codeFences = true        # å¯ç”¨ Markdown ä»£ç å—ï¼ˆ```ï¼‰
    guessSyntax = true       # è‡ªåŠ¨æ£€æµ‹ä»£ç è¯­è¨€
    hl_Lines = ""            # æ”¯æŒé«˜äº®ç‰¹å®šè¡Œï¼ˆä¾‹å¦‚ "1-3,5"ï¼‰
    lineNoStart = 1          # è¡Œå·ä» 1 å¼€å§‹
    lineNos = true           # æ˜¾ç¤ºè¡Œå·
    lineNumbersInTable = true # å°†è¡Œå·æ”¾åœ¨è¡¨æ ¼ä¸­ï¼Œæ”¹å–„æ ·å¼
    noClasses = false        # ä½¿ç”¨ CSS ç±»ï¼ˆè€Œä¸æ˜¯å†…è”æ ·å¼ï¼‰
    style = "monokai"        # é«˜äº®æ ·å¼ï¼ˆå¯é€‰æ‹© monokai, dracula ç­‰ï¼‰
    tabWidth = 4             # åˆ¶è¡¨ç¬¦å®½åº¦